bigman:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  
  
  # Group Position Torque Controllers ---------------------------------------
  group_position_torque_controller:
    type: custom_effort_controllers/JointGroupPositionEffortController
    joints: [LHipLat,
LHipYaw,
LHipSag,
LKneeSag,
LAnkSag,
LAnkLat,
RHipLat,
RHipYaw,
RHipSag,
RKneeSag,
RAnkSag,
RAnkLat,
WaistLat,
WaistSag,
WaistYaw,
LShSag,
LShLat,
LShYaw,
LElbj,
LForearmPlate,
LWrj1,
LWrj2,
NeckYawj,
NeckPitchj,
RShSag,
RShLat,
RShYaw,
RElbj,
RForearmPlate,
RWrj1,
RWrj2]
             
    ps: [6500.0,
1063.0,
6500.0,
6500.0,
6500.0,
6500.0,
6500.0,
1063.0,
6500.0,
6500.0,
6500.0,
6500.0,
4000.0,
5500.0,
4000.0,
1500.0,
1500.0,
1500.0,
1500.0,
200.0,
200.0,
200.0,
100.0,
500.0,
1500.0,
1500.0,
1500.0,
1500.0,
200.0,
200.0,
200.0]
            
    is: [0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0,
0.0]
              
    ds: [10.0,
10.0,
10.0,
10.0,
10.0,
10.0,
10.0,
10.0,
10.0,
10.0,
10.0,
10.0,
40.0,
55.0,
40.0,
10.0,
10.0,
10.0,
10.0,
5.0,
5.0,
5.0,
1.1,
5.5,
10.0,
10.0,
10.0,
10.0,
5.0,
5.0,
5.0]
